version: "3.8"

services:

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: bmi_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend_api
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://admin:password123@postgres:5432/bmi_db
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: bmi_db
      DB_USER: admin
      DB_PASSWORD: password123
      PORT: 3000
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: frontend_app
    restart: always
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:3000
    ports:
      - "5173:5173"

volumes:
  pgdata: