apiVersion: v1
kind: ConfigMap

metadata:
  name: app-config
  namespace: three-tier-app

data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: bmi_db
  API_URL: http://backend-service:3000

  DATABASE_URL: postgresql://admin:password123@postgres-service:5432/bmi_db